spring.config.import=optional:application-secret.properties
spring.application.name=backend

spring.datasource.url=${databaseUrl}

spring.datasource.username=${databaseUsername}
spring.datasource.password=${databasePassword}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.allow-circular-references=true

spring.jpa.defer-datasource-initialization=true  
# run hibernate first then schema.sql
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

jwt.secretKey=${jwtsecretKey}
# default admin username : riteshdudhbhate11@gmail.com
# pass word : 1234
