spring.config.import=optional:application-secret.properties
spring.application.name=backend

spring.datasource.url=${databaseUrl}

spring.datasource.username=${databaseUsername}
spring.datasource.password=${databasePassword}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.mail.host=${MAIL_HOST:smtp-relay.brevo.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:${mailUsername}}
spring.mail.password=${MAIL_PASSWORD:${mailPassword}}
spring.mail.properties.mail.smtp.from=${MAIL_FROM:${mailFrom:${spring.mail.username}}}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.main.allow-circular-references=true


spring.jpa.defer-datasource-initialization=true  
# this above line meand first run hibernet then schema.sql
#spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

jwt.secretKey=${jwtsecretKey}
# default admin username : riteshdudhbhate11@gmail.com
# pass word : 1234
